#ifndef ULLLAS_PLC_H
#define ULLLAS_PLC_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Packet Loss Concealment. When the receiver detects a gap in seq, it
 * fills the gap with samples generated by plc_conceal(). With PLC off
 * (default) we fill with silence so the timing stays aligned. With PLC
 * on we hold the last frame for ~5 ms then linearly fade to silence -
 * very cheap, no extra latency, and inaudible for short losses.
 *
 * The receiver always inserts concealment frames into the ring buffer
 * on loss so the audio callback isn't forced into an underrun. That
 * keeps drift compensation and jitter accounting consistent.
 */

typedef struct {
    int          channels;
    int          enabled;
    unsigned int fade_frames; /* full-amplitude fade length */
    int32_t      last_frame[16];
} PlcState;

void plc_init(PlcState *s, int channels, unsigned int sample_rate, int enabled);

/* Snapshot the most recent received frame for use as the hold source.
 * Pass NULL for `last_frame_interleaved` if no good frame to snapshot. */
void plc_observe_packet(PlcState *s, const int32_t *interleaved, int num_frames);

/* Write `frames` interleaved concealment frames to `out_interleaved`. */
void plc_conceal(PlcState *s, size_t frames, int32_t *out_interleaved);

#ifdef __cplusplus
}
#endif

#endif
